### PR TITLE
Kf 2015

### PR DESCRIPTION
**Pull request by kylefiedler**
27e9373a-deda-4a3f-8ec4-323c2367e4cc
27fc0f5e-0ac2-4276-830b-b914c357a8df
d5706434-8ed4-4fd1-804c-9c41cd7470f0
faa15f96-a030-4dfd-b95a-e3f4eef373c8

### CODE REVIEW

**Comment by kylefiedler** [comment]
@daigofuji Take a look at this let me know if I need to make any changes.

**Comment by kylefiedler** [comment]
I need to make some adjustments to that boston background photo

**Comment by daigofuji** [comment]
This is absolutely gorgeous. Thank you for doing all this!!!

**Comment by daigofuji** [comment]
Added some text update, but this is awesome! I am pulling the trigger!

**Comment by adarowski** [comment]
:heart: :heart_eyes: :heart:

**Comment by daigofuji** [comment]
It is beautiful.

**Pull request merged**
